# Generated by Django 4.1 on 2022-08-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_touristspot_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='comments',
        ),
    ]
