# Generated by Django 4.1 on 2022-08-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0001_initial'),
        ('comments', '0001_initial'),
        ('core', '0004_remove_touristspot_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='avaliations',
            field=models.ManyToManyField(to='avaliations.avaliations'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
