# Generated by Django 4.1 on 2022-08-15 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0002_rename_avaliations_avaliation'),
        ('comments', '0001_initial'),
        ('atractions', '0001_initial'),
        ('addresses', '0001_initial'),
        ('core', '0005_touristspot_avaliations_touristspot_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='atractions',
            field=models.ManyToManyField(blank=True, null=True, to='atractions.atractions'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='avaliations',
            field=models.ManyToManyField(blank=True, null=True, to='avaliations.avaliation'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comments.comment'),
        ),
    ]
