# Generated by Django 4.1 on 2022-08-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atractions', '0001_initial'),
        ('comments', '0001_initial'),
        ('avaliations', '0002_rename_avaliations_avaliation'),
        ('core', '0006_touristspot_address_alter_touristspot_atractions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='atractions',
            field=models.ManyToManyField(to='atractions.atractions'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='avaliations',
            field=models.ManyToManyField(to='avaliations.avaliation'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
