# Generated by Django 4.1 on 2022-08-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0007_alter_touristspot_atractions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
